### ISSUE TITLE
Deploy API and Web UI via Cloud Run to manage gcloudrig

### ISSUE THREAD

**Issue by putty182** [gcloudrig/gcloudrig-cloud-run#2]
From https://github.com/gcloudrig/gcloudrig/pull/77

> - [x] Add some buttons to call the endpoints 
> - [x] Fix up some console issues
> - [x] Maintain last command run logs in case of page reload
> - [ ] Step by step builder for setup.sh api call
> - [x] Serve angular from express
> - [x] Use GCP secret manager for username & passwords?
> - [x] Test on cloud run
> - [ ] Write deploy for setup

**Comment by oschwartz10612** [comment]
I have been looking though your commits. All great stuff that I was too lazy to do before! ; ) Thank you!

**Comment by putty182** [comment]
I'm done for the night and have it in a state where it more or less runs with the Gitpod stuff, except for #5 which seems to be preventing the built angular app from being able to do much.

I'm not sure if this is the best way to go about running it (actually i know it's not the best way, but it is certainly *a* way).

If I have any further commits i'll make them by PR so feel free to hack away :)

**Comment by oschwartz10612** [comment]
Okay. I will get going on some work tonight for me I think. 

What do you mean not the best way? Putting everything in cloud run? I agree, but it makes it simple for now...

**Comment by oschwartz10612** [comment]
Moved remaining items to the project which I should have been using all along
